#!/bin/dash

# Copyright (c) 2014 - 2016 Luigi Tarenga <luigi.tarenga@gmail.com>
# Distributed under the terms of a MIT license.

#run this script at boot before sshd starts. this ensure that
#in case of crash the local lockdir_* is unlocked

export LANG=C

cd ${0%/*}

log () { [ -n "$verbose" ] && echo $@ >&2 ; }

rm -f temp/lockdir_sh/*
rmdir temp/lockdir_*
mkdir temp/lockdir_un

log good. lock server ready.
