#!/bin/dash

# Copyright (c) 2014 - 2016 Luigi Tarenga <luigi.tarenga@gmail.com>
# Distributed under the terms of a MIT license.

# parameters: [ lock_name ]

export LANG=C

cd ${0%/*}

lname=${1:-default}

read lock_servers < conf/lock_servers
read rpath        < conf/remote_path
read sshopt       < conf/sshopt

if [ -f temp/${lname}_counter ] ; then
   read counter  < temp/${lname}_counter
   read holder term seq previous < temp/${lname}_htsp

   echo local term seq for $lname:
   echo holder:  $holder
   echo term:    $term
   echo seq:     $seq
   echo counter: $counter
   echo previous: $previous
else
   echo lock $lname not initialized
fi

read hostname majority < temp/${lname}_params

echo
echo remote state sequence for $lname:
echo lock_server holder term seq
for h in $lock_servers ; do
   echo $h: $(ssh $sshopt $h "cd $rpath ; " \
                             "[ -f state/$lname ] && " \
                             "cat state/$lname || " \
                             "echo lock file not found")
done
echo
