#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

#run this script at boot before sshd start. this ensure that
#in case of crash the activity_lock is unlocked

export LANG=C

cd ${0%/*}

log () { [ -n "$verbose" ] && echo $@ >&2 ; }

rm -f temp/activity_lockdir_sh/*
rmdir temp/activity_lockdir_*
mkdir temp/activity_lockdir_un

log good. lock server ready.
