#!/bin/dash

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

# input: lock_name

export LANG=C
export sshopt="-o ControlPath=~/.ssh/dex-lock-socket-%h -o ControlMaster=auto \
-o ConnectTimeout=1 -o ServerAliveInterval=2 -o ServerAliveCountMax=3 \
-o PasswordAuthentication=no -o StrictHostKeyChecking=no -q"

cd ./${0%/*}

lname=${1:-default}

read lock_servers < conf/lock_servers
read rpath        < conf/remote_path
read holder   < temp/${lname}_holder
read term     < temp/${lname}_term
read value    < temp/${lname}_value
read hostname < temp/hostname

log () { [ -n "$verbose" ] && echo $@ >&2 ; }

#
# if holder send release request
#
if [ "$holder" = "$hostname" ] ; then
   value=$((value+1))
   release=true
   for h in $lock_servers ; do
      ssh $sshopt $h cd $rpath \; internals/increase-value $hostname $lname $term $value $release \
         > temp/${h}_${lname}_output < /dev/null &
   done

   wait
fi

echo "-invalid-" > temp/${lname}_holder
echo "0" > temp/${lname}_term
echo "0" > temp/${lname}_value
pkill -x -f "ssh -MNf -o ControlPath=~/.ssh/dex-lock-server-socket-%h"
log good. lock released
