#!/bin/sh

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

# parameters: [ lock_name ]

cd ${0%/*}

lname=${1:-default}
read holder term value previous < temp/${lname}_htvp
echo $previous
