#!/bin/dash

# Copyright (c) 2014 - 2016 Luigi Tarenga <luigi.tarenga@gmail.com>
# Distributed under the terms of a MIT license.

# input:  lock_name seq
# return: success holder term seq

lname=$1
seq=$2
success=false

if [ -f state/${lname} ] ; then
   read s_holder s_term s_seq < state/${lname}
else
   s_holder="-invalid-"
   s_term=0
   s_seq=0
fi

[ "$seq" -lt "$s_seq" ] && success=true
echo $success $s_holder $s_term $s_seq
