#!/bin/sh

#Copyright (c) 2014 Luigi Tarenga <luigi.tarenga@gmail.com>
#Distributed under the terms of a MIT license.

# input:  holder lock_name term value [ release ]
# return: success holder term value

holder=$1
lname=$2
term=$3
value=$4
release=$5
success=false

if [ -f state/${lname} ] ; then
   read s_holder s_term s_value < state/${lname}
else
   s_term=0
   s_value=0
fi

if [ "$value" -gt "$s_value" ] ; then
   #found a higher value. there is a live holder
   s_holder=$holder
   s_term=$term
   s_value=$value
   if [ "$release" = "true" ] ; then
      s_holder="-invalid-"
   fi
   echo $s_holder $s_term $s_value > state/${lname}
fi

if [ "$term" -eq "$s_term" -a "$value" -eq "$s_value" -a "$holder" = "$s_holder" ] ; then
   success=true
fi

echo $success $s_holder $s_term $s_value
