#!/bin/dash

# Copyright (c) 2014 - 2016 Luigi Tarenga <luigi.tarenga@gmail.com>
# Distributed under the terms of a MIT license.

# input:  holder lock_name term seq [ release ]
# return: success holder term seq

holder=$1
lname=$2
term=$3
seq=$4
release=$5
success=false

if [ -f state/${lname} ] ; then
   read s_holder s_term s_seq < state/${lname}
else
   s_term=0
   s_seq=0
fi

if [ "$seq" -gt "$s_seq" ] ; then
   #found a higher seq. there is a live holder
   s_holder=$holder
   s_term=$term
   s_seq=$seq
   if [ "$release" = "true" ] ; then
      s_holder="-invalid-"
   fi
   echo $s_holder $s_term $s_seq > state/${lname}
fi

if [ "$term" -eq "$s_term" -a "$seq" -eq "$s_seq" -a "$holder" = "$s_holder" ] ; then
   success=true
fi

echo $success $s_holder $s_term $s_seq
