#!/bin/dash

# Copyright (c) 2014 - 2016 Luigi Tarenga <luigi.tarenga@gmail.com>
# Distributed under the terms of a MIT license.

export LANG=C

quit () {
   rm temp/lockdir_sh/$$ > /dev/null 2>&1 < /dev/null && \
   rmdir temp/lockdir_sh > /dev/null 2>&1 < /dev/null && \
   mkdir temp/lockdir_un > /dev/null 2>&1 < /dev/null
   exit $1
}

trap 'quit 0' HUP INT TERM

until
   mv temp/lockdir_un temp/lockdir_sh > /dev/null 2>&1 < /dev/null
   ( mkdir -p temp/lockdir_sh ; echo "" > temp/lockdir_sh/$$ ) > /dev/null 2>&1 < /dev/null
do
   if [ -n "$lock_timeout" ] ; then
      lock_timeout=$((lock_timeout-1))
      [ "$lock_timeout" -lt 0 ] && exit 1
   fi

   sleep 0.1 2> /dev/null
done

"$@"
quit $?
